Catches the error thrown by require and tries again
